---
- hosts: all
  become: yes
  tasks:
    - name: I want to install java jdk8 on ubuntu server
      apt:
        name: openjdk-8-jdk
        state: present

        when: ansible_os_family=="Debian"

    - name: I want to install java jdk8 on RedHat server
      yum:
           name: openjdk-8-jdk
           state: present
    
           when: ansible_os_family=="RedHat" 