---
- hosts: all
  become: yes
  tasks:

    - name: i want to install java jdk8 on ubuntu server
      apt:
        name: openjdk-8-jdk
        state: present
  
  when: ansible_os_family=="Debian"

---
- hosts: all
  become: yes
  tasks:

    - name: i want to install jva jdk8 on RedHat sever
      apt:
        name: java-1.8.0-openjdk
        state: present

 when: ansible_os_family=="RedHat"